export const themes = {
    "ambiance": "Ambiance",
    "chaos": "Chaos",
    "chrome": "Chrome",
    "clouds": "Clouds",
    "clouds_midnight": "Clouds Midnight",
    "cobalt": "Cobalt",
    "crimson_editor": "Crimson Editor",
    "dawn": "Dawn",
    "dracula": "Dracula",
    "dreamweaver": "Dreamweaver",
    "eclipse": "Eclipse",
    "github": "Github",
    "gob": "Gob",
    "gruvbox": "Gruvbox",
    "idle_fingers": "Idle Fingers",
    "iplastic": "iPlastic",
    "katzenmilch": "Katzenmilch",
    "kr_Theme": "KR Theme",
    "kuroir": "Kuroir",
    "merbivor": "Merbivor",
    "merbivor_soft": "Merbivor Soft",
    "mono_industrial": "Mono Industrial",
    "monokai": "Monokai",
    "nord_dark": "Nord Dark",
    "pastel_on_dark": "Pastel On Dark",
    "solarized_dark": "Solarized Dark",
    "solarized_light": "Solarized Light",
    "sqlserver": "SQLServer",
    "terminal": "Terminal",
    "textmate": "Textmate",
    "tomorrow": "Tomorrow",
    "tomorrow_night": "Tomorrow Night",
    "tomorrow_night_blue": "Tomorrow Night Blue",
    "tomorrow_night_bright": "Tomorrow Night Bright",
    "tomorrow_night_eighties": "Tomorrow Night 80s",
    "twilight": "Twilight",
    "vibrant_ink": "Vibrant Ink",
    "xcode": "Xcode"
}